### ISSUE TITLE
Support for selectionCriteriaType = other ?

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting-extensions/ocds_selectionCriteria_extension#1]
eForms has four codes for "Selection Criteria Type" (`selectionCriteriaType`):

- technical
- financial
- suitability
- other

Do we add "other" in the code list of the extension, and/or do we add a `selectionCriteriaOtherType` to capture that other type?

**Comment by jpmckinney** [comment]
We can add 'other', since that seems to be what ESPD uses.

Generally, I prefer to encourage users to add their own codes, instead of using 'other', but in this case, since it matches another system/standard, I think it's fine.

**Comment by jpmckinney** [comment]
By the way – I have a script that configures extension repos to not have any issues, as it makes it harder for maintainers to find issues. For extensions, we instead open issues in https://github.com/open-contracting/ocds-extensions/issues
